### PR TITLE
GUI.py -> Gui.py [Main.py]

### PR DESCRIPTION
**Pull request by imsaptarshi**
Refactored `os.system('python ./App/GUI.py')` to `os.system('python ./App/Gui.py')` (Line:9)

### CODE REVIEW

**Comment by akionsight** [comment]
Love your pull request and sorry for the spaghetti code we wrote. We are planning to merge your changes but will take some time (about 3 weeks) before we can safely merge this PR as this project is for the 3rd timathon and we have been strictly advised to not make any changes to the repo until the competition ends

**Comment by akionsight** [comment]
Until then please explain the changes in this PR briefly

**Comment by akionsight** [comment]
And thanks for contributing 😁

**Comment by Abdesol** [comment]
Hello @saptarshibasu15 ,
Is it working now?
and btw I need to ask one question.
Many websites are down right?
Discord, Fiverr, ... are not opening for me.
Fiverr shows the below image and discord doesn't show an error but doesn't work anymore.
If you guys are facing the same thing please announce me. : )
Screenshot 2021-02-21 070650

**Comment by akionsight** [comment]
I think fiverr is down

**Comment by Abdesol** [comment]
I am contacting them right now

**Pull request merged**
